module.exports = {
    fbId: '',
    fbSecret: '',
    twitterId: '',
    twitterSecret: '',
    googleId: '',
    googleSecret: '',    
    linkedInId: '',
    linkedInSecret: '',
    gitId: '',
    gitSecret: '',
    fbDevId: '',
    fbDevSecret: '',
    twitterDevId: '',
    twitterDevSecret: '',
    googleDevId: '',
    googleDevSecret: '',
    linkedInDevId: '',
    linkedInDevSecret: '',
    gitDevId: '',
    gitDevSecret: ''
};
